schema_version = "1.0.0"

id = "reforge"
name = "Reforge"
version = "0.5.2"

tagline = "Reforge Blender scenes into Defold assets"

type = "add-on"

maintainer = "Alexander Bulatov"

license = [
  "SPDX:GPL-3.0-or-later",
]

blender_version_min = "4.2.0"

website = "https://github.com/ufgo/defold-export-for-blender"
